version: '3'

services:
  paybyrdapi:
    image: paybyrd
    build:
      context: .
    ports:
      - "8001:80"
    networks:
      - paybyrd-network

networks: 
    paybyrd-network:
        driver: bridge